vaadin.launch-browser=true
spring.application.name=student_registration
spring.mongodb.uri=mongodb+srv://${MONGO_USER}:${MONGO_PASS}@cluster0.yrwktnl.mongodb.net/student_registration?appName=cluster0
spring.data.mongodb.auto-index-creation=true
spring.profiles.active=dev
