vaadin.launch-browser=true
spring.application.name=student_registration
spring.mongodb.uri=mongodb+srv://student_registration_test:123@cluster0.yrwktnl.mongodb.net/student_registration?appName=cluster0
spring.data.mongodb.auto-index-creation=true
spring.profiles.active=dev
